# Generated by Django 3.0.5 on 2020-04-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuteMisho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='nombre')),
                ('message', models.CharField(max_length=200, verbose_name='mensaje')),
            ],
        ),
    ]
